import Head from 'next/head';
import Link from 'next/link';
import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';

// Next.js page component
export default function HomePage() {
  const [posts, setPosts] = useState([]);
  const router = useRouter();

  useEffect(() => {
    async function fetchPosts() {
      try {
        const response = await fetch('/api/posts');
        const data = await response.json();
        setPosts(data);
      } catch (error) {
        console.error('Error fetching posts:', error);
      }
    }

    fetchPosts();
  }, []);

  const handleCreatePost = () => {
    router.push('/create-post');
  };

  return (
    <div className="container">
      <Head>
        <title>Next.js App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1 className="title">
          Welcome to <Link href="/">Next.js!</Link>
        </h1>

        <button onClick={handleCreatePost}>
          Create New Post
        </button>

        <div className="grid">
          {posts.map((post) => (
            <div key={post.id} className="card">
              <h3>{post.title}</h3>
              <p>{post.content}</p>
              <Link href={`/posts/${post.id}`}>
                <a>Read More</a>
              </Link>
            </div>
          ))}
        </div>
      </main>

      <footer>
        <a href="https://nextjs.org" target="_blank" rel="noopener noreferrer">
          Powered by Next.js
        </a>
      </footer>
    </div>
  );
}

// API route example (would be in pages/api/posts.js normally)
// export async function getServerSideProps(context) {
//   // Fetch data from external API
//   const res = await fetch(`https://.../posts`);
//   const posts = await res.json();
//
//   // Pass data to the page via props
//   return { props: { posts } };
// }